// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEXivZWpMiCPrFs4f8PuzEmdhc0af9P1M',
    appId: '1:878778908300:web:f35dac147c38c4c33a85a9',
    messagingSenderId: '878778908300',
    projectId: 'shoptest-eacc5',
    authDomain: 'shoptest-eacc5.firebaseapp.com',
    storageBucket: 'shoptest-eacc5.firebasestorage.app',
    measurementId: 'G-VPS0EMNQZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnz_Gh3-to5Rfcq5CV0_3ED5vVxpf7YBw',
    appId: '1:878778908300:android:41df5478b350651c3a85a9',
    messagingSenderId: '878778908300',
    projectId: 'shoptest-eacc5',
    storageBucket: 'shoptest-eacc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCPzPl6tfXQwWy1S6jEWKg2aWNxo8OpAo',
    appId: '1:878778908300:ios:844d67c45fe44fba3a85a9',
    messagingSenderId: '878778908300',
    projectId: 'shoptest-eacc5',
    storageBucket: 'shoptest-eacc5.firebasestorage.app',
    iosBundleId: 'com.example.testShop',
  );
}
